### ISSUE TITLE
Poor connection detection issue

### ISSUE THREAD

**Issue by Adelmaer** [grinder81/nfreachability#1]
I've tried this framework in my app to check if the device is online or offline.

It works fine to detect online/offline cases.

Except for these cases: The case when we have a poor internet connection or network is low (on 3g for example) or when we have the internet (3g) but the plan is not paid and it is doesn't send or receive anything, or when the user goes to a subway where the internet connection is extremely slow or when the WiFi is active but it doesn't work.

If we have such cases, framework returns connected state. But actually, this is not true.

Is there any way to detect such poor network or internet not available cases?

I'm using Xcode Version 10.0, Swift 4

**Comment by grinder81** [comment]
I think these are 2 different things. In any application you have 2 part for a network:

- Do you have any connectivity?
- Can you reach your endpoint?

This library was targeted the first one to detect very quick. To do handle poor connection or endpoint reachability you have to make a call and find proper status, which completely related to the call that you are doing.

I remember they mentioned in Apple talk that you can get status on your call from URLSession manager. That will be network library.

**Comment by Adelmaer** [comment]
Thanks
